version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-stretch
    steps:
        - checkout

        - run:
            name: Provide package-lock.json
            command:  if [ ! -f package.json ];then; touch package-lock.json; fi

        # Download and cache dependencies
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

        - run:
            name: Installing Dependencies
            command: if [ ! -f package.json ];then; npm install; fi

        - run:
            name: Installing Helix CLI
            command: npm install @adobe/helix-cli --save=false

        - save_cache:
            paths:
                - node_modules
            key: v1-dependencies-{{ checksum "package-lock.json" }}

        - run:
            name: Building Templates
            command: npx hlx build

        - run:
            name: Showing Working Copy Status
            command: git status

        - run:
            name: Deploying to Adobe I/O Runtime
            command: npx hlx deploy --no-auto --dirty

        - run:
            name: Activate CDN
            command: npx hlx publish

        - run:
            name: Test Performance
            command: npx hlx perf
